setwd("E:\\ADI BUANA\\LAST")

life_asean = read.csv("life-expectancy.csv")
head(life_asean)

library(tidyverse)
library(dplyr)
library(gganimate)
library(gapminder)

df <- life_asean %>%
  filter(Entity == "Brunei"|
           Entity == "Cambodia" |
           Entity == "Indonesia" |
           Entity == "Malaysia" |
           Entity == "Myanmar" |
           Entity == "Laos" |
           Entity == "Singapore" |
           Entity == "Philippines" |
           Entity == "Thailand" |
           Entity == "Timor" |
           Entity == "Vietnam")

head(df) 


theme_set(theme_classic())

words <- scan(
  text="Life Expectancy Shout East Asia ",
  what= character())

pattern <- paste0("(",words,")",collapse="|")

df  <- subset(df, !grepl(pattern, Entity , ignore.case = TRUE))


colnames(df) <- gsub("Entity", "country", colnames(df))
colnames(df) <- gsub("Code", "code", colnames(df))
colnames(df) <- gsub("Life.Expectancy", "lifeexpectancy", colnames(df))
colnames(df) <- gsub("Year", "year", colnames(df))

df$Life.expectancy <- round(df$Life.expectancy/1)


dflife <- df %>%
  group_by(year) %>%
  # The * 1 makes it possible to have non-integer ranks while sliding
  mutate(rank = min_rank(-Life.expectancy) * 1,
         Value_rel = Life.expectancy/Life.expectancy[rank==1],
         Value_lbl = paste0(" ",Life.expectancy)) %>%
  filter(rank <=11) %>%
  ungroup()


p2 <- ggplot(dflife, aes(rank, group = country, 
                     fill = as.factor(country), color = as.factor(country))) +
  geom_tile(aes(y = Life.expectancy/2,
                height = Life.expectancy,
                width = 0.9), alpha = 0.8, color = NA) +
  geom_text(aes(y = 0, label = paste(country, " ")), vjust = 0.2, hjust = 1) +
  geom_text(aes(y=Life.expectancy,label = Value_lbl, hjust=0)) +
  coord_flip(clip = "off", expand = FALSE) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_reverse() +
  guides(color = FALSE, fill = FALSE) +
  
  labs(title='{closest_state}', x = "", y = "Life Expectancy (years)",
       caption = "Sources: World Bank | Plot generated by Antonito HC @antowilcoxon") +
  theme(plot.title = element_text(hjust = 0, size = 22),
        axis.ticks.y = element_blank(),  # These relate to the axes post-flip
        axis.text.y  = element_blank(),  # These relate to the axes post-flip
        plot.margin = margin(1,1,1,4, "cm")) +
  
  transition_states(year, transition_length = 4, state_length = 1) +
  ease_aes('cubic-in-out')

plot(p2)


animate(p2, 200, fps = 10, duration = 80, width = 800, height = 600, renderer = gifski_renderer("gganim.gif"))



p4 <- df  %>%
  # build rank, labels and relative values
  group_by(year) %>%
  mutate(Rank = rank(-Life.expectancy),
         value_rel = Life.expectancy/Life.expectancy[Rank==1],
         value_lbl = paste0(" ",round(Life.expectancy/1)))  %>%
  group_by(country) %>%
  # keep top 10
  filter(Rank <= 11) %>%
  # plot
  ggplot(aes(-Rank,value_rel, fill = country)) +
  geom_col(width = 0.8, position="identity") +
  coord_flip() + 
  geom_text(aes(-Rank,y=0,label = country,hjust=0)) +       #country label
  geom_text(aes(-Rank,y=value_rel,label = value_lbl, hjust=0)) + # value label
  theme_minimal() +
  theme(legend.position = "none",axis.title = element_blank()) +
  # animate along Year
  transition_states(year,4,1)

animate(p4, 100, fps = 25, duration = 70, width = 800, height = 600)
